name: Consul | AspNetCore

on:
  push:
  pull_request:

jobs:

  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    name: Consul | AspNetCore
    runs-on: windows-2019

    steps:
      - name: Consul | AspNetCore | Checkout
        uses: actions/checkout@v2

      - name: Consul | AspNetCore | .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.404

      - name: Consul | AspNetCore | Build
        run: dotnet build -c=Release -p:TreatWarningsAsErrors=true

      - name: Consul | AspNetCore | Tests
        run: |
          cd Consul.AspNetCore.Test
          dotnet test -c=Release --no-build -v=Normal
          cd ..

      - name: Consul | AspNetCore | Package
        run: |
          if ("${{ github.ref }}" -like "refs/tags/Consul.AspNetCore_v*") {
            $tag = "${{ github.ref }}".SubString(29)
            $version = (Select-Xml -path Consul.AspNetCore/Consul.AspNetCore.csproj -XPath "/Project/PropertyGroup/VersionPrefix/text()").node.Value
            if (-not ($tag -eq $version)) {
              echo "There is a mismatch between the project version ($version) and the tag ($tag)"
              exit 1
            }
          } else {
            # WORKAROUND: Add letter prefix to ensure that MSBuild treats
            # the suffix as a string. e.g. '0313071' will fail as an invalid
            # version string, but 'G0313071' will succeeded. It looks like
            # the parser does not like numbers with a leading zero.
            $suffix = 'g' + $(git rev-parse --short HEAD)
            $params = "--version-suffix", $suffix
          }
          dotnet pack -c=Release --no-build @params Consul.AspNetCore/Consul.AspNetCore.csproj

      - name: Consul | AspNetCore | Package | Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuget-aspnetcore-package
          path: dist/consul.aspnetcore

  # Publish NuGet package when a tag is pushed.
  # Tests need to succeed first, including having a tag name that matches the version number.
  publish:
    if: startsWith(github.ref, 'refs/tags/Consul.AspNetCore_v')
    needs: build
    runs-on: windows-2019
    steps:
      - name: Consul | AspNetCore | Package | Artifact | Download
        uses: actions/download-artifact@v2
        with:
          name: nuget-aspnetcore-package
          path: dist/consul.aspnetcore

      - name: Consul | AspNetCore | Package | Publish
        run: dotnet nuget push dist/consul.aspnetcore/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
