name: Nudge

on:
  workflow_run:
    workflows: [CI,CodeQL]
    types: [completed]
    branches: [master]


jobs:
  nudge:
    runs-on: ubuntu-latest
    environment: nudge
    steps:
      - name: Send notification
        uses: pavlovic-ivan/octo-nudge@v2
        with:
          webhooks: ${{ secrets.NUDGE_WEBHOOKS }}